### ISSUE TITLE
Command line call of script

### ISSUE THREAD

**Issue by Wolf92pt** [douglasrizzo/detection_util_scripts#2]
Hi.

First of all thank you very much for placing this scripts.
I am having some issues in calling the functions. It doesn't recognize the directory links.
Could you provide a example of what to call together with the function?

Thank you.
Sorry.

**Comment by douglasrizzo** [comment]
All the scripts have help messages that describe how to use them and what the arguments mean. I suggest you try to execute one of the scripts with the `-h` flag in your terminal and read the help message.

For example, `python generate_csv.py -h` describes all the arguments of the script.

If you still have doubts, post here again.

**Comment by douglasrizzo** [comment]
@Wolf92pt I just re-read your question and realized you are trying to call the functions from inside the scripts and that is not how they are supposed to be used. You're supposed to run the scripts via the command line, _e.g._ by running

    python generate_tfrecord.py [arguments...]

Again, you can find out which arguments each script expects by calling the script with the `-h` flag. I just added this explanation to the README, in hopes this may help future users.
