### ISSUE TITLE
List index out of range - generate_tfrecords.py

### ISSUE THREAD

**Issue by khany27** [douglasrizzo/detection_util_scripts#4]
Hello,

For TF 2.x, I tried generating the tfrecords from csv and images directly. However, it failed saying
`
 File "generate_tfrecord.py", line 147, in <module>
    class_dict = class_dict_from_pbtxt(args.pbtxt_input)
  File "generate_tfrecord.py", line 114, in class_dict_from_pbtxt
class_dict[names[i]] = ids[i]
IndexError: list index out of range`

**Comment by douglasrizzo** [comment]
Thanks for the report. I believe the problem might be related to the contents of your label map. The entries may not be numbered sequentially. Can you check that or share your label map with me?

**Comment by mineymax** [comment]
Hello,
Thanks for the article. I got the same problem, if create a tfrecords from more than one id in label_map.pbtxt file.
I checked the object list in csv file and it was exactly the same as in pbtxt. Please correct it and thank you in advance.
TF 2.2.0
my label_map.pbtxt

```
item {
    id: 1
    name: 'A'
}

item {
    id: 2
    name: 'B'
}

item {
    id: 3
    name: 'C'
}
```

**Comment by douglasrizzo** [comment]
Please test the new master branch, as I believe the problem has been fixed. Unfortunately, I don't have an image dataset to test the fix, but I fixed the specific bug that caused the reported issue.

**Comment by douglasrizzo** [comment]
@khany27 @mineymax can you confirm that the problem was resolved?

**Comment by mineymax** [comment]
I tested yesterday, the problem was solved very well, **thank you very much.** 
However, I would like to keep it updated some line of code to be compatible with tensorflow 2.x (i.e. tf.gfile.GFile update to tf.io.gfile.GFile and tf.python_io.TFRecordWriter to tf.io.TFRecordWriter)

**Comment by douglasrizzo** [comment]
There is already a pull request with that change, which I will merge as soon as possible.
