### ISSUE TITLE
filename = group.filename.encode('utf8')

### ISSUE THREAD

**Issue by julio8a** [douglasrizzo/detection_util_scripts#8]
Getting this error when generating the tfrecords.

```
  File "generate_tfrecord.py", line 31
    filename = group.filename.encode('utf8')
                                           ^
IndentationError: unindent does not match any outer indentation level
```

generating the csv and pbtxt worked fine.

**Comment by layshowl** [comment]
我也是出现了这个问题，求大神指点

**Comment by julio8a** [comment]
@layshowl,

I ended up using a different generate_tf file from the repository this fork came from and it worked for me:
https://github.com/datitran/raccoon_dataset/blob/master/generate_tfrecord.py

if you have multiple classes you're trying to detect, i.e. Apple, Banana, and Peach then you need to modify line 32 to look like this:

```
    if row_label == 'Apple':
        return 1
    elif: row_label == 'Banana':
        return 2
    elif: row_label == 'Peach':
        return 3
    else:
        None
```

**Comment by douglasrizzo** [comment]
I fixed the indentation problem on master. It came from a PR.
